code4sac/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'code4sac.views.home', name='home'),
    url(r'^openworld/', include('openworld.urls', namespace='openworld')),
    url(r'^accounts/profile/$', 'openworld.views.dashboard', name='dashboard'),
    url(r'^accounts/login/$', 
       'django.contrib.auth.views.login', {
    'template_name': 'openworld/login.html'
    }), 
        
    url(r'^admin/', include(admin.site.urls)),
)

openworld/urls.py
from django.conf.urls import patterns, url
from openworld import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),
    url(r'^login/$', 'django.contrib.auth.views.login', {
        'template_name': 'openworld/login.html'
    }, name='login'),
    url(r'^info/$', views.user_info, name='info'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^viewentries/$', views.view_entries, name='viewentries'),
    url(r'^viewentry/(?P<entry_id>\d+)/$', views.view_entry, name='viewentry'),
    url(r'^taggedentries/$', views.tagged_entries, name='taggedentries'),
    url(r'^submitnewrequest/$', views.submit_new_request, name='submitnewrequest'),
    url(r'^submitrequest/$', views.submit_request, name='submitrequest'),
    url(r'^submittags/$', views.submit_tags, name='submittags'),
    url(r'^tagsform/(?P<entry_id>\d+)/$', views.tags_form, name='tagsform'),
    url(r'^viewrequests/$', views.view_requests, name='viewrequests'),
    url(r'^register/$', views.register, name='register'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
)

openworld/models.py
from django.db import models
from django.contrib.auth.models import User
from openworld.utils.fields import JSONField

class Source(models.Model):
    name = models.CharField(max_length=64, unique=True, null=False) 
    description = models.CharField(max_length=1024)
    url = models.CharField(max_length=1024)
    phone = models.CharField(max_length=32)
    created_date = models.DateField('date created', auto_now_add=True)
    modified_date = models.DateField('date modified', auto_now=True)

    def __str__(self):
        return self.name

    def __iter__(self):
        for i in self._meta.get_all_field_names():
            yield (i, getattr(self, i))

class Entry(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=512)
    city = models.CharField(max_length=32)
    state = models.CharField(max_length=16)
    country = models.CharField(max_length=64)
    tags = JSONField(blank=True, null=True)
    created_date = models.DateField('date created', auto_now_add=True)
    modified_date = models.DateField('date modified', auto_now=True)

    def __str__(self):
        return self.name

    def __iter__(self):
        for i in self._meta.get_all_field_names():
            yield (i, getattr(self, i))

class ExtraEntry(models.Model):
    entry = models.OneToOneField(Entry, on_delete=models.CASCADE)
    url = models.CharField(max_length=1024)
    agency = models.CharField(max_length=64)
    agency_url = models.CharField(max_length=1024)
    phone = models.CharField(max_length=32)
    icarol_id = JSONField(blank=True, null=True)

    def __str__(self):
        return self.entry.name

    def __iter__(self):
        for i in self._meta.get_all_field_names():
            yield (i, getattr(self, i))

class Pending(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    source = models.CharField(max_length=64, null=False)
    url = models.CharField(max_length=1024)
    data = JSONField(blank=True, null=False)
    created_date = models.DateField('date created', auto_now_add=True)
    modified_date = models.DateField('date modified', auto_now=True)

    def __str__(self):
        return self.source

    def __iter__(self):
        for i in self._meta.get_all_field_names():
            yield (i, getattr(self, i))

class TagModifications(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    entry = models.ForeignKey(Entry, null=False, on_delete=models.CASCADE)
    tags = JSONField(blank=True, null=False)
    created_date = models.DateField('date created', auto_now_add=True)

    def __str__(self):
        return self.entry.name

    def __iter__(self):
        for i in self._meta.get_all_field_names():
            yield (i, getattr(self, i))

openworld/forms.py
from django import forms
from django.contrib.auth.models import User
from openworld.models import Source

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')

class RequestForm(forms.Form):
    sources = Source.objects.all()
    source = forms.ModelChoiceField(queryset=sources, label="Source:")
    file = forms.FileField(label="File:")

class NewRequestForm(forms.Form):
    source = forms.CharField(required=True)
    url = forms.URLField(required=False)
    file = forms.FileField(label="File:")

openworld/views.py
from django.shortcuts import render, render_to_response
from django.contrib.auth.views import logout
from django.contrib.auth.decorators import login_required
from django.template import RequestContext, loader
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from openworld.forms import UserForm, RequestForm, NewRequestForm
from openworld.models import Entry, ExtraEntry, TagModifications, Pending
from django.core.urlresolvers import reverse
from django.contrib import messages
import json


def index(request):
    with open('openworld/taxonomy.json', 'r') as f:
        jsondata = json.load(f)
    return render(request, 'openworld/index.html', {'taxonomy':jsondata})


def search(request):
    services_term = request.GET['servicesquery']
    situations_term = request.GET['situationsquery']
 
    services_query_tags = json.loads('["%s"]' % services_term.replace(',','","'))
    situations_query_tags = json.loads('["%s"]' % situations_term.replace(',','","'))

    results = []
    for entry in Entry.objects.all():
        if entry.tags:
            entry_tags = json.loads(entry.tags)
            situations_tags = entry_tags['situations']
            services_tags = entry_tags['services']
            if any(tag in situations_query_tags for tag in situations_tags) or any(tag in services_query_tags for tag in services_tags):
                results.append(entry)

    paginator = Paginator(results, 30)
    page = request.GET.get('page')
    try:
        paged_results = paginator.page(page)
    except PageNotAnInteger:
        paged_results = paginator.page(1)
    except EmptyPage:
        paged_results = paginator.page(paginator.num_pages)
    return render(request, 'openworld/search.html', {'results':paged_results})


@login_required
def dashboard(request):
    latest_entries = Entry.objects.order_by('-id')
    paginator = Paginator(latest_entries, 30)

    page = request.GET.get('page')
    try:
        entries = paginator.page(page)
    except PageNotAnInteger:
        entries = paginator.page(1)
    except EmptyPage:
        entries = paginator.page(paginator.num_pages)

    context = {"entries": entries}
    return render(request, 'openworld/dashboard.html', context)


@login_required
def user_info(request):
    return render(request, 'openworld/profile.html', {"profile": request.user})


@login_required
def view_entries(request):
    latest_entries = Entry.objects.order_by('-id')
    paginator = Paginator(latest_entries, 30)

    page = request.GET.get('page')
    try:
        entries = paginator.page(page)
    except PageNotAnInteger:
        entries = paginator.page(1)
    except EmptyPage:
        entries = paginator.page(paginator.num_pages)

    context = {"entries": entries}
    return render(request, 'openworld/viewentries.html', context)


@login_required
def view_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    extra_entry = ExtraEntry.objects.get(entry=entry)

    if extra_entry.url and extra_entry.url[:7] != "http://":
        extra_entry.url = "http://" + extra_entry.url
    if extra_entry.agency_url and extra_entry.agency_url[:7] != "http://":
        extra_entry.agency_url = "http://" + extra_entry.agency_url
    return render(request, 'openworld/viewentry.html', {'entry': entry, 'extra_entry': extra_entry})


@login_required
def tagged_entries(request):
    try:
        latest_entries = TagModifications.objects.filter(user=request.user).order_by('-id')
        paginator = Paginator(latest_entries, 30)

        page = request.GET.get('page')
        try:
            entries = paginator.page(page)
        except PageNotAnInteger:
            entries = paginator.page(1)
        except EmptyPage:
            entries = paginator.page(paginator.num_pages)

        context = {"entries": entries}
    except:
        context = {"entries": None}
    return render(request, 'openworld/taggedentries.html', context)


@login_required
def view_requests(request):
    try:
        latest_entries = Pending.objects.filter(user=request.user).order_by('-id')
        paginator = Paginator(latest_entries, 30)

        page = request.GET.get('page')
        try:
            entries = paginator.page(page)
        except PageNotAnInteger:
            entries = paginator.page(1)
        except EmptyPage:
            entries = paginator.page(paginator.num_pages)

        context = {"entries": entries}
    except:
        context = {"entries": None}
    return render(request, 'openworld/viewrequests.html', context)


@login_required
def submit_request(request):
    if request.method == 'POST':
        form = RequestForm(request.POST, request.FILES)
 
        if form.is_valid():
            cleaned_data = form.cleaned_data
            try:
                jsondata = json.loads(cleaned_data['file'].read().decode())
                if type(jsondata) is list or not jsondata.get('data'):
                    jsondata = {'data':jsondata}
            except ValueError:
                messages.success(request, 'Error: Invalid JSON file')
                return HttpResponseRedirect(reverse('dashboard'))

            pending = Pending(user=request.user, source=cleaned_data['source'], url=cleaned_data['source'].url, data=jsondata) 
            pending.save()
            messages.success(request, 'Success: Request submitted.')
            return HttpResponseRedirect(reverse('dashboard'))
        else:
            messages.error(request, 'Error: Request submission failed.')
            return HttpResponseRedirect(reverse('dashboard'))
    else:
        form = RequestForm()
        return render(request, 'openworld/submitrequest.html', {'form':form})


@login_required
def submit_new_request(request):
    if request.method == 'POST':
        form = NewRequestForm(request.POST, request.FILES)
 
        if form.is_valid():
            cleaned_data = form.cleaned_data
            try:
                jsondata = json.loads(cleaned_data['file'].read().decode())
                if type(jsondata) is list or not jsondata.get('data'):
                    jsondata = {'data':jsondata}
            except ValueError:
                messages.success(request, 'Error: Invalid JSON file')
                return HttpResponseRedirect(reverse('dashboard'))

            pending = Pending(user=request.user, source=cleaned_data['source'], url=cleaned_data['url'], data=jsondata) 
            pending.save()
            messages.success(request, 'Success: Request submitted.')
            return HttpResponseRedirect(reverse('dashboard'))
        else:
            messages.error(request, 'Error: Request submission failed.')
            return HttpResponseRedirect(reverse('dashboard'))
    else:
        form = NewRequestForm()
        return render(request, 'openworld/submitrequest.html', {'form':form, 'new_request':True})


@login_required
def submit_tags(request):
    if request.method == 'POST':
        entry = Entry.objects.filter(id=request.POST['id'])

        if not entry:
            messages.error(request, 'Error: entry does not exist.')
            return HttpResponseRedirect(reverse('dashboard'))
        entry = entry[0]

        try:
            services_tags = json.loads('["%s"]' % request.POST['servicestags'].replace(',', '","'))
            situations_tags = json.loads('["%s"]' % request.POST['situationstags'].replace(',', '","'))
        except ValueError:
            messages.error(request, 'Error: Invalid json format.')
            return HttpResponseRedirect(reverse('dashboard'))
 
        # If tags are empty or user has elevated privileges, then replace the tags
        if not entry.tags or request.user.is_staff or request.user.is_superuser:
            entry.tags = {'services':services_tags, 'situations':situations_tags}
        else:
            # Otherwise just append new tags only
            entry_tags = json.loads(entry.tags)
            if situations_tags and not situations_tags == [""]:
                new_situations_tags = list(set(entry_tags['situations']).union(set(situations_tags)))
            else:
                new_situations_tags = entry_tags['situations']

            if services_tags and not services_tags == [""]:
                new_services_tags = list(set(entry_tags['services']).union(set(services_tags)))
            else:
                new_services_tags = entry_tags['services']

            entry.tags = {'situations': new_situations_tags, 'services': new_services_tags}
            
        entry.save()
        tag_modification = TagModifications(user=request.user, entry=entry, tags=entry.tags) 
        tag_modification.save()

        # Success
        return render(request, 'openworld/submittags.html', {'postrequest':request.POST}) 
    else:
        messages.error(request, 'Error: Request submission failed.')
        return HttpResponseRedirect(reverse('dashboard'))


@login_required
def tags_form(request, entry_id):
    entry = Entry.objects.get(id=entry_id)

    with open('openworld/taxonomy.json', 'r') as f:
        jsondata = json.load(f)
    return render(request, 'openworld/submittags.html', {'taxonomy':jsondata, 'entry_id':entry_id, 'entry_tags':entry.tags})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/openworld/')


def register(request):
    context = RequestContext(request)
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()

    return render_to_response(
            'openworld/register.html',
            {'user_form': user_form, 'registered': registered},
            context)

openworld/templates/openworld/dashboard.html
<html>
<head>
    <title>OpenWorld Dashboard: {{ user.username }}</title>
    {% load staticfiles %}
    <link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
    <link href="{% static "openworld/style.css" %}" rel="stylesheet" type="text/css" />

    <link href="http://aehlke.github.io/tag-it/css/jquery.tagit.css" rel="stylesheet" type="text/css">
    <link href="http://aehlke.github.io/tag-it/css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="http://aehlke.github.io/tag-it/js/tag-it.js" type="text/javascript" charset="utf-8"></script>
    <script src="{% static "openworld/taxonomy.js" %}" type="text/javascript" charset="utf-8"></script>

    <script src="{% static "openworld/dashboard.js" %}" type="text/javascript" charset="utf-8"></script>
</head>
<body>
    <div id="container">

    <div id="title">
        <p><h1>OpenWorld Dashboard</h1></p>
    </div>
    <p style="margin:0px; text-align: center;">
        <a class="link" id="entries" href="{% url 'openworld:viewentries' %}">main</a> | 
        <a href="{% url 'openworld:index' %}">search</a> | 
        <a class="link" href="{% url 'openworld:info' %}"> profile info</a> | 
        <a class="link" href="{% url 'openworld:taggedentries' %}">your tagged entries</a> | 
        <a class="link" href="{% url 'openworld:viewrequests' %}">your submission requests</a> |
        <a class="link" href="{% url 'openworld:submitrequest' %}">submit a request</a> | 
        <a href="{% url 'openworld:logout' %}">logout</a>
    </p>

    {% if messages %}
    <style>
        ul.messages {
            list-style-type: none;
            margin: 0px;
            padding: 0px;
            color: white;
        }
        li.success {
            background-color: olivedrab;
        }
        li.error {
            background-color: red;
        }
    </style>

    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    <script>$("ul.messages").fadeOut(5000);</script>
    {% endif %}

    </br>
    <div id="content"></div>
    </div>
</body>
</html>

openworld/templates/openworld/index.html
<html>
<head>
    <title>OpenWorld</title>
    {% load staticfiles %}
    <link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
    <link href="{% static "openworld/style.css" %}" rel="stylesheet" type="text/css" />

    <link href="http://aehlke.github.io/tag-it/css/jquery.tagit.css" rel="stylesheet" type="text/css">
    <link href="http://aehlke.github.io/tag-it/css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="http://aehlke.github.io/tag-it/js/tag-it.js" type="text/javascript" charset="utf-8"></script>
    <script src="{% static "openworld/taxonomy.js" %}" type="text/javascript" charset="utf-8"></script>

</head>
<body>
    <div id="container">
        <div id="title">
            <p><h1>OpenWorld</h1></p>
        </div>
        <div style="text-align: center;">
        <form id="searchForm" method="GET" action="{% url 'openworld:search' %}">
            {% csrf_token %}
            <input id="situationskeywords" type="text" name="situationsquery" autocomplete="off" />
            <input id="serviceskeywords" type="text" name="servicesquery" autocomplete="off" />
            <input type="submit" value="Search" />
        </form>

        <p>
            <a href="{% url 'openworld:dashboard' %}">Login/Dashboard</a> | 
            <a href="{% url 'openworld:register' %}">Register</a>
        </p>

        {% if taxonomy %}
        <div style="display: inline-block; ;margin: 0 auto;">
        <div style="float:left; width:200px;">
            <ul id="scroll-situations" style="list-style-type: none;">
                <li><b class="scrolltitle">Situations</b></li>
            </ul>
            <ul id="situations" style="list-style-type: none;">
                {% for situation in taxonomy.situations %}
                <li>{{ situation }}</li>
                {% endfor %}
            </ul>
        </div>
        <div style="float:left; width:200px;">
            <ul id="scroll-services" style="list-style-type: none;">
                <li><b class="scrolltitle">Services</b></li>
            </ul> 
            <ul id="services" style="list-style-type: none;">
                {% for service in taxonomy.services %}
                <li>{{ service }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <script>
        $(document).ready(function(){
            $("#situations").hide();
            $("#services").hide();    
        });
        $("#scroll-situations").click(function () {
            $("#situations").slideToggle("slow");
        }); 
        $("#scroll-services").click(function () {
            $("#services").slideToggle("slow");
        });         
        $("#situationskeywords").tagit({
            availableTags: situations,
            beforeTagAdded: function(event, ui) {
                if($.inArray(ui.tagLabel, situations) == -1) { return false; }
            },
            tagSource: situations,
            removeConfirmation: true,
            placeholderText: "I am...",
            allowDuplicates: false,
            allowSpaces: true,    
        });
        $("#serviceskeywords").tagit({
            availableTags: services,
            beforeTagAdded: function(event, ui) {
                if($.inArray(ui.tagLabel, services) == -1) { return false; }
            },
            tagSource: services,
            removeConfirmation: true,
            placeholderText: "I want...",
            allowDuplicates: false,
            allowSpaces: true,    
        });
        </script>
        <style>
        ul
        {
            margin-left: 0px;
            padding-left: 0px;
        }
        </style>

        </div>
        </div>
    </div>
</body>
</html>

openworld/templates/openworld/register.html
<html>
<head>
    <title>OpenWorld: Register</title>
    {% load staticfiles %}
    <link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
    <link href="{% static "openworld/style.css" %}" rel="stylesheet" type="text/css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
</head>
<body>
<div id="container">
    <div id="title">
        <p><h1>Register with OpenWorld</h1></p>
    </div>
    {% if registered %}
    <p><strong>Thank you for registering!</strong></p>
    <p><a href="{% url 'openworld:index' %}">Return</a> or <a href="{% url 'openworld:login' %}">Login</a></p>
    {% else %}
    <form id="user_form" method="post" action="{% url 'openworld:register' %}"
            enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        <input type="submit" name="submit" value="Register" />
    </form>
    {% endif %}
</div>
</body>
</html>

openworld/templates/openworld/search.html
<html>
<head>
    <title>OpenWorld</title>
    {% load staticfiles %}
    <link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
    <link href="{% static "openworld/style.css" %}" rel="stylesheet" type="text/css" />

    <link href="http://aehlke.github.io/tag-it/css/jquery.tagit.css" rel="stylesheet" type="text/css">
    <link href="http://aehlke.github.io/tag-it/css/tagit.ui-zendesk.css" rel="stylesheet" type="text/css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="http://aehlke.github.io/tag-it/js/tag-it.js" type="text/javascript" charset="utf-8"></script>
    <script src="{% static "openworld/taxonomy.js" %}" type="text/javascript" charset="utf-8"></script>
</head>
<body>
    <div id="container">
        <div id="title">
            <p><h1>OpenWorld</h1></p>
        </div>
        <div style="text-align: center;">
        <form id="searchForm" method="GET" action="{% url 'openworld:search' %}">
            {% csrf_token %}
            <input id="situationskeywords" type="text" name="situationsquery" autocomplete="off" />
            <input id="serviceskeywords" type="text" name="servicesquery" autocomplete="off" />
            <input type="submit" value="Search" />
        </form>

        <script>
        $("#situationskeywords").tagit({
            availableTags: situations,
            beforeTagAdded: function(event, ui) {
                if($.inArray(ui.tagLabel, situations) == -1) { return false; }
            },
            tagSource: situations,
            removeConfirmation: true,
            placeholderText: "I am...",
            allowDuplicates: false,
            allowSpaces: true,    
        });
        $("#serviceskeywords").tagit({
            availableTags: services,
            beforeTagAdded: function(event, ui) {
                if($.inArray(ui.tagLabel, services) == -1) { return false; }
            },
            tagSource: services,
            removeConfirmation: true,
            placeholderText: "I want...",
            allowDuplicates: false,
            allowSpaces: true,    
        });
        </script>

        <p>
            <a href="{% url 'openworld:dashboard' %}">Login/Dashboard</a> | 
            <a href="{% url 'openworld:register' %}">Register</a>
        </p>

        <table>
        {% for result in results %}
            <tr>
                <td><a href="{% url 'openworld:viewentry' entry_id=result.id %}">{{ result.name }}</a></td>
                <td>{{ result.description }}</td><td></td>
                <td>{{ result.tags }}</td>
            </tr>
        {% endfor %}
        </table>

        <div class="pagination">
            <span class="step-links">
                {% if results.has_previous %}
                    <a href="?page={{ results.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ results.number }} of {{ results.paginator.num_pages }}.
                </span>

                {% if results.has_next %}
                    <a href="?page={{ results.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        </div>
    </div>
</body>
</html>

openworld/templates/openworld/submitrequest.html
{% if jsonerror %}
<p style="color: red;">{{ jsonerror }}</p>
{% endif %}

{% if form.errors %}
    <p style="color: red;">
        Form has errors. Correct the error{{ form.errors|pluralize }} below.
    </p>
    {{ form.errors }}</br>
    {{ form.non_field_errors }}
{% endif %}

{% if new_request %}
<b>new</b>
<form id="submitrequest" action="{% url 'openworld:submitnewrequest' %}" method="post" enctype="multipart/form-data">
{% else %}
<form id="submitrequest" action="{% url 'openworld:submitrequest' %}" method="post" enctype="multipart/form-data">
{% endif %}
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit"/>
</form>

{% if not new_request %}
<p><a href="javascript:void(0);" onclick="loadEntry( '{% url 'openworld:submitnewrequest' %}' )">Submit a new source</a></p>
{% endif %}

openworld/templates/openworld/viewentries.html
<div class="pagination">
    <div id="ajax_table_result">
    <table>
        <tr class="title">
            <td class="latest">Id</td>
            <td class="latest">User</td>
            <td class="latest">Name</td>
            <td class="latest">Tags</td>
        <tr>
        {% for entry in entries %}
        <tr>
            <td class="latest"><a href="javascript:void(0);" onclick="loadEntry( '{% url 'openworld:viewentry' entry_id=entry.id %}' )">{{ entry.id }}</a></td>
            <td class="latest">{{ entry.user }}</td>
            <td class="latest">{{ entry.name }}</td>
            <td class="latest">{{ entry.tags }}</td>
        </tr>
        {% endfor %}
    </table>
    </div>
    <hr width="300px">
    <span class="step-links">
        {% if entries.has_previous %}
            <a id="prev" href="?page={{ entries.previous_page_number }}">previous</a>
        {% else %}
            <span>previous</span>
        {% endif %}

        <span class="current">
             | {{ entries.number }} of {{ entries.paginator.num_pages }} | 
        </span>

        {% if entries.has_next %}
            <a id="next" href="{{ request.path }}?page={{ entries.next_page_number }}">next</a>
        {% else %}
            <span>next</span>
        {% endif %}
    </span>
</div>

openworld/templates/openworld/viewentry.html
<ul class="profile">
    <li><b>Id:</b> {{ entry.id }}</li>
    <li><b>Name:</b> {{ entry.name }}</li>
    <li><b>Author:</b> {{ entry.user.username }}</li>
    <li><b>Source:</b> {{ entry.source.name }}</li>
    <li><b>Description:</b> {{ entry.description }}</li>
    <li><b>City:</b> {{ entry.city }}</li>
    <li><b>State:</b> {{ entry.state }}</li>
    <li><b>Country:</b> {{ entry.country }}</li>
    <li><b>Tags:</b> {{ entry.tags }} <a href="javascript:void(0);" onclick="loadEntry( '{% url 'openworld:tagsform' entry_id=entry.id %}' )">(Add/Modify Tags)</a></li>
    <li><b>Created Date:</b> {{ entry.created_date }}</li>
    <li><b>Modified Date:</b> {{ entry.modified_date }}</li>
</ul>
<br/>
<b>Additional Fields:</b>
<ul class="profile">
    {% if extra_entry.url %}<li><b>Url:</b> <a href="{{ extra_entry.url }}">{{ extra_entry.url }}</a></li>{% endif %}
    {% if extra_entry.agency %}<li><b>Agency:</b> {{ extra_entry.agency }}</li>{% endif %}
    {% if extra_entry.agency_url %}<li><b>Agency Url:</b> <a href="{{ extra_entry.agency_url }}">{{ extra_entry.agency_url }}</a></li>{% endif %}
    {% if extra_entry.phone %}<li><b>Phone:</b> {{ extra_entry.phone }}</li>{% endif %}
    {% if extra_entry.icarol_id %}<li><b>iCarol Id:</b> {{ extra_entry.icarol_id }}</li>{% endif %}
</ul>